### ISSUE TITLE
Set text element as "Title" type. 

### ISSUE THREAD

**Issue by ghost** [evidenceprime/html-docx-js#79]
Is there any way to set a text-element as Title?

![image](https://user-images.githubusercontent.com/39584027/42151033-ed78a128-7ddb-11e8-8ce3-8464b470dff3.png)

I tried looking through the mso attributes but I'm unsure.

**Comment by PabloCC** [comment]
Set this in the css property:

`h1 {
      mso-style-name:"Headline 1";
      mso-style-unhide:no;
      mso-style-qformat:yes;
      
      /* Headline Style */
      font-weight: normal;
      font-family: 'Source Sans Pro SemiBold';
      font-size: 24pt;
 }`

**Comment by PabloCC** [comment]
Set this in the css property:
```css
h1 {
mso-style-name:"Headline 1";
mso-style-unhide:no;
mso-style-qformat:yes;
font-weight: normal;
font-family: 'Source Sans Pro SemiBold';
font-size: 24pt;
}

```
